name: Docker image build and push to DockerHub

on: push

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   
   - name: docker build csharp
     run: |
       docker build ./c# -t aimvector/csharp:1.0.0
   - name: checking docker images
     run: |
       docker images ls
