name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: docker logout
      run: |
        docker logout
        
    - name: docker login 
      run: |
        docker --version
        
    - name: docker login
      run: |
        sudo docker login -u praveendevops1337 -p 9ec686ffD@1
        
    - name: docker image search
      run: |
        docker images  
        
    

        
        
        
   
