name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: docker logout
      run: |  
        docker logout
    - name: docker login
      run: |
        docker login -u praveendevops1337 -p 9ec686ffD@1
    - name: docker build csharp
      run: |
        docker build ./c# -t praveendevops1337/csharp:1.0.0
    - name: docker build nodejs
      run: |
        docker build ./nodejs -t praveendevops1337/nodejs:1.0.0
    - name: docker build python
      run: |
        docker build ./python -t praveendevops1337/python:1.0.0
    - name: docker build golang
      run: |
        docker build ./golang -t praveendevops1337/golang:1.0.0
        
    - name: docker images
      run: |  
        docker images
        
    - name: docker push
      run: |
        docker push aimvector/csharp:1.0.0
        docker push aimvector/nodejs:1.0.0
        docker push aimvector/golang:1.0.0
        docker push aimvector/python:1.0.0
